### ISSUE TITLE
JEI Search Crash

### ISSUE THREAD

**Issue by DinnerBeef** [GizmoTheMoonPig/OpenBlocksTrophies#13]
### Mod Version

 OpenBlocksTrophies-1.20.1-3.0.4

### Crash Report (if applicable)

https://s.dinnerbeef.com/gOXe5/Jeqereko79.txt

### Bug Description

Searching "Phyt" in JEI will cause the game to crash.

### Steps to Reproduce

Search for "phyt" in JEI

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this crash will also occur if you try to spawn the Afrit from Occultism: make sure you're using the correct version of SmartBrainLib since forge decided to break a bunch of stuff: https://www.curseforge.com/minecraft/mc-mods/smartbrainlib/files/4763247
Alternatively, most modders recommend sticking to 47.1.3 for now or moving to use neoforge instead.

**Comment by DinnerBeef** [comment]
Ahh, I see there is a neoforge version. Hope that fixes it.
