### ISSUE TITLE
[Compat] Cobblemon Compatibility

### ISSUE THREAD

**Issue by ghost** [GizmoTheMoonPig/OpenBlocksTrophies#25]
### Mod Suggestion

https://www.curseforge.com/minecraft/mc-mods/cobblemon

### Why Should It Be in the Mod?

Would be fun to be able to collect trophies of all the Cobblemons. It's a pretty popular mod and it would be nice to see compatibility for it.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.
- [X] I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.

**Comment by GizmoTheMoonPig** [comment]
this will be a task and a half since I do the trophy configs by hand so it may take me a while, just as a warning

**Comment by ghost** [comment]
> this will be a task and a half since I do the trophy configs by hand so it may take me a while, just as a warning

Oh wow I had no idea these were done manually! I highly appreciate you even considering this since theres is quite a lot of mobs. I assume the fact that they are still adding new ones every now and then doesn't make things easier. Wether it happens or not I just want you to know I really enjoy your mod.

**Comment by GizmoTheMoonPig** [comment]
after looking into this, I unfortunately can't support it the way I want to. 
Turns out all cobblemon use the same entity, meaning I have less control over the trophy appearance. While it is possible for me to add all of them thanks to my variant system, I can't scale the variants themselves meaning the sizes of the displayed entities will be all over the place instead of staying consistent with all the other trophies. Sorry :(

**Comment by ghost** [comment]
> 

No worries! I appreciate you looking into it.
