### ISSUE TITLE
naturalist

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#3]
### Mod Version

latest

### Client Log

d

### Crash Report (if applicable)

d

### Bug Description

all the naturalist trophies dosnt excist

### Steps to Reproduce

just having the mod

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
I tried adding them all last time I did a wave of trophies and turns out some of the mobs don't work as trophies. There's still a problem with Geckolib that basically allows mobs to still play animations even when they aren't actually real and that really irritates me. Any mobs that do that have been skipped. I'll keep an eye out, and if they ever fix that I will add them back in.

**Comment by GreenForzeGaming** [comment]
ah, that is unfortunate
