### ISSUE TITLE
[Suggestion] Items / Block Displays?

### ISSUE THREAD

**Issue by DinnerBeef** [GizmoTheMoonPig/OpenBlocksTrophies#46]
### The Suggestion

Hello, I was mainly wondering if it is possible to have items / block displays render on the trophies. I tried a few things, including using the json to add a new one. I was trying giving myself via command, but they just render blank.
Likewise, I don't know if I am doing something wrong or if it does not work do to how they render. I tied both of these below to avail. 
```
obtrophies:trophy[obtrophies:trophy_info={entity:"minecraft:block_display",variant:{block_state:{Name:"minecraft:emerald_block"}}}]
obtrophies:trophy[obtrophies:trophy_info={entity:"minecraft:item",variant:{Item:{id:"cobblestone"}}}]
``` 

### Why Should It Be in the Mod?

If this can be done. It would be nice if pack dev can give out some nice-looking trophies for doing things. 

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by DinnerBeef** [comment]
To add on to this. If this cant be done, no big deal. There are other ways this can be done. It's just easier/ nicer looking if it can be done inside this mod.

**Comment by GizmoTheMoonPig** [comment]
Currently, this cant be done in the mod as only mobs support proper displaying (player trophies are a bit of a special case). I do however *really* like this idea so I absolutely would not mind adding support for displaying blocks and items. I don't know if what you need this for is time sensitive at all or just a thought, but I don't know when I'll be able to do this as I have quite a few other projects on my plate at the moment. This will definitely be something I work on in a future update though

**Comment by DinnerBeef** [comment]
Amazing. Yea, I don't know all the way. However, I can do stuff with spawn eggs for now and move over to the trophies. If stuff happens before release. It should be straightforward to move stuff over :)

**Comment by GizmoTheMoonPig** [comment]
I finally got to work on this! 
The system im putting in place works a bit differently than my entity trophies, as the data is directly attached to the trophy rather than being a registry via json files. I did, however, write a nifty little command to generate these display trophies! You can currently customize these things:
- the item displayed
- the scale of the item (1 by default)
- the offset of the item on the pedestal (0, 0, 0 by default)
- the initial rotation of the item (0, 0, 0, by default)
- the rotation speed of the item, allowing it to spin on the pedestal (0 by default)
- whether an item bobs on the pedestal or not (false by default)
- the sound the trophy plays when right clicked (nothing by default)

If there are any other customization things you would like to see for this please let me know and i'll be more than happy to add them. Heres a little example vid of some things you can do :) 
https://github.com/user-attachments/assets/1f1b12a2-94dc-4029-9985-4cc80aa328ce

**Comment by DinnerBeef** [comment]
O my. This looks spectacular. This will be quite useful.

**Comment by DinnerBeef** [comment]
Any idea when a release will be available?

**Comment by GizmoTheMoonPig** [comment]
I'll try to get a build out within a week. This week has been hectic and I havent had much time to do anything

**Comment by GizmoTheMoonPig** [comment]
Just pushed a build for 1.20.1, 1.20.4, and 1.21. Hopefully theyll be approved shortly. Enjoy!
